services:
  online-reservations-app:
    container_name: online-reservations-app
    image: ghcr.io/amsolenberg/sdev265_group1:latest
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks:
      - online-reservations_net
    ports:
      - ${ONLINE_RESERVATIONS_APP_3000:-3000}:3000
    depends_on:
      - online-reservations-db

  online-reservations-db:
    container_name: online-reservations-db
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo-data:/data/db
    networks:
      - online-reservations_net
    ports:
      - ${ONLINE_RESERVATIONS_DB_27017:-27017}:27017

networks:
  online-reservations_net:
    driver: bridge

volumes:
  mongo-data: