services:
  online-reservations:
    container_name: online-reservations
    image: node:23
    working_dir: /app
    command: >
      sh -c "npm install && npm start"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - online-reservations_net
    ports:
      - 3002:3000

  online-reservations_db:
    container_name: online-reservations_db
    image: mongo
    restart: unless-stopped
    env_file: ./env/mongo.env
    volumes:
      - ./database:/data/db
    networks:
      - online-reservations_net
    ports:
      - 27018:27017

networks:
  online-reservations_net:
    driver: bridge